project:
  type: website
  output-dir: docs

website:
  title: "git-tutorial-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - presentation.qmd
      - github-slides.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
